name: LPKoth
version: '${project.version}'
main: lpkoth.lupino.dev.LPKoth
api-version: '1.21'
author: Lupino1
description: Simple lightweight koth plugin
commands:
  koth:
    description: Main koth command
    permission: lpkoth.basecommand

permissions:
  lpkoth.basecommand:
    default: op
  lpkoth.admin:
    default: op
